<?xml version="1.0"?>
<!-- Revolute-Revolute Manipulator -->
<robot name="{{cookiecutter.robot_name}}" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:include
    filename="$(find {{cookiecutter.package_name}})/urdf/{{cookiecutter.robot_name}}.gazebo" />
  <xacro:include
    filename="$(find {{cookiecutter.package_name}})/urdf/{{cookiecutter.robot_name}}.materials" />
  <xacro:include
    filename="$(find {{cookiecutter.package_name}})/urdf/{{cookiecutter.robot_name}}.macro" />

  <xacro:property name="mass" value="1" /> <!-- arbitrary value for mass -->
  <xacro:property name="width" value="0.1" /> <!-- Square dimensions (widthxwidth) of beams -->
  <xacro:property name="height1" value="2" /> <!-- Link 1 -->
  <link name="world" />

  <joint name="base2world" type="fixed">
    <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
    <parent link="world" />
    <child link="base_link" />
  </joint>

  <link name="base_link">
    <collision>
      <origin xyz="0 0 ${height1/2}" rpy="0 0 0" />
      <geometry>
        <box size="${width} ${width} ${height1}" />
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${height1/2}" rpy="0 0 0" />
      <geometry>
        <box size="${width} ${width} ${height1}" />
      </geometry>
      <material name="orange" />
    </visual>

    <xacro:box_inertia mass="${mass}" w="${width}" h="${height1}" />
  </link>

</robot>